version: "3.3"


services:
  nats1:
    container_name: nats1
    image: nats-streaming
    networks: 
      nattest:
        ipv4_address: 172.16.0.2
  natsapp:
    container_name: nats_helper
    build:
      context: .
      dockerfile: Dockerfile    
    depends_on:
      - nats1
    command: go test -v
networks:
  nattest:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24